snapcraft-version: 8.2.10
snapcraft-started-at: '2024-06-13T15:20:52.328938Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '24.04'
name: bluez
version: 5.72-1
summary: Bluetooth tools and daemons
description: |
  This package contains tools and system daemons for using Bluetooth
  devices. BlueZ is the official Linux Bluetooth protocol stack. It
  is an Open Source project distributed under GNU General Public
  License (GPL). See the project homepage for more details:
  https://github.com/snapcore/bluez-snap/tree/snap-24
base: core24
grade: stable
confinement: strict
apps:
  bluetoothctl:
    command: bin/client-wrapper usr/bin/bluetoothctl
    plugs:
    - client
    - uhid
  bluez:
    command: bin/bluetoothd-wrapper
    bus-name: org.bluez
    daemon: dbus
    slots:
    - service
    - dbus-bluez
    plugs:
    - uhid
    - uinput
    - kernel-crypto-api
  hciconfig:
    command: usr/bin/hciconfig
    plugs:
    - bluetooth-control
  hcidump:
    command: usr/bin/hcidump
    plugs:
    - bluetooth-control
    - network-control
    - home
  hciattach:
    command: usr/bin/hciattach
    plugs:
    - bluetooth-control
    - serial-port
  btattach:
    command: usr/bin/btattach
    plugs:
    - bluetooth-control
    - serial-port
  hcitool:
    command: usr/bin/hcitool
    plugs:
    - bluetooth-control
  sdptool:
    command: usr/bin/sdptool
    plugs:
    - client
  btmon:
    command: usr/bin/btmon
    plugs:
    - bluetooth-control
    - network-control
    - home
  btmgmt:
    command: usr/bin/btmgmt
    plugs:
    - bluetooth-control
    - network-control
parts:
  bluez-common:
    plugin: dump
    source: bin/
    organize:
      client-wrapper: bin/client-wrapper
      bluetoothd-wrapper: bin/bluetoothd-wrapper
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  changelog:
    plugin: nil
    override-build: 'cp "/build/ci-bluez-snosdknar1i8se76"/ChangeLog "$CRAFT_PART_INSTALL"

      '
    organize:
      ChangeLog: snap/ChangeLog
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
    - dpkg-dev
    - git
    - python3-docutils
    stage-packages:
    - bluez-hcidump=5.72-0ubuntu5
    - bluez=5.72-0ubuntu5
    - libasound2-data=1.2.11-1build2
    - libasound2t64=1.2.11-1build2
    - libdw1t64=0.190-1.1build4
    override-build: |
      set -ex
      find "$CRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/bluez*' \
           -delete
      find "$CRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$CRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$CRAFT_PART_INSTALL"/build-tools
    prime:
    - usr/share/doc/bluez
    - usr/share/doc/bluez-hcidump
    stage: []
  bluez:
    after:
    - stack-snaps-tools
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/bluez
    source-type: git
    source-branch: applied/ubuntu/noble
    autotools-configure-parameters:
    - --prefix=/usr
    - --libexec=/usr/lib/
    - --enable-experimental
    - --enable-threads
    - --disable-cups
    - --disable-systemd
    - --disable-silent-rules
    - --enable-test
    - --enable-deprecated
    - CFLAGS='-O2 -Wl,-z,relro,-z,now -pie -fpie'
    build-packages:
    - flex
    - bison
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libcap-ng-dev
    - udev
    - libudev-dev
    - libreadline-dev
    - libical-dev
    - libjson-c-dev
    - check
    - python3-pygments
    prime:
    - usr/lib/bluetooth/bluetoothd
    - usr/bin/bluetoothctl
    - usr/bin/hciconfig
    - usr/bin/hcidump
    - usr/bin/hciattach
    - usr/bin/btattach
    - usr/bin/hcitool
    - usr/bin/sdptool
    - usr/bin/btmon
    - usr/bin/btmgmt
    override-build: |
      set -ex
      "/build/ci-bluez-snosdknar1i8se76/stage"/build-tools/check-versions bluez yes
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "/build/ci-bluez-snosdknar1i8se76"/patch/*
      craftctl default
      cp tools/btmgmt "$CRAFT_PART_INSTALL"/usr/bin/
      # Strip binaries
      find "$CRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-.*executable\|application/x-.*sharedlib' | cut -d: -f1 | xargs strip
      # Run all tests shiped by default
      make check
    stage-packages: []
    stage: []
architectures:
- amd64
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/+snap/ci-bluez-snosdknar1i8se76/+build/2512162
build-packages: []
build-snaps: []
primed-stage-packages:
- bluez-hcidump=5.72-0ubuntu5
- bluez=5.72-0ubuntu5
